// <auto-generated />
namespace HelmesBootcamp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class servicelane : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(servicelane));
        
        string IMigrationMetadata.Id
        {
            get { return "201703152142212_service-lane"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
